name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - name: Setup Node.js@lts environment
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run lint:css
      - run: pnpm run build
